cart/urls.py
from django.urls import path
from django.contrib.auth import get_user_model
from . import views

User = get_user_model()

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
]

iheartpins/urls.py
from accounts import urls
import accounts
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views as auth_views
# from accounts import views as account_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # path('register/', account_views.register, name='register'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('cart/', include('cart.urls', namespace='cart'), name='cart'),
    path('orders/', include('orders.urls', namespace='orders'), name='orders'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('main.urls', namespace='main'), name='main'),
    path('', include('trans.urls', namespace='trans'), name='transaction')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, redirect
import json

from trans.models import Listing
from .cart import Cart


def cart_detail(request):
    cart = Cart(request)
    # if request.user.is_authenticated:
    #     user = request.user
    # else:
    #     # Create empty cart for now for non-logged in user
    #     items = []
    #
    # context = {'items': items}
    #
    remove_from_cart = request.GET.get('remove_from_cart', '')
    change_quantity = request.GET.get('change_quantity', '')
    quantity = request.GET.get('quantity', 0)

    if remove_from_cart:
        cart.remove(remove_from_cart)
        return redirect('cart:cart')

    if change_quantity:
        cart.add(change_quantity, quantity, True)
        return redirect('cart:cart')

    return render(request, 'cart/cart.html')


# def update_cart(request):
#     data = json.loads(request.data)
#     listing_id = data['listing']
#     action = data['action']
#
#     user = request.user
#     listing = Listing.objects.get(id=listing_id)
#
#     return render(request,'cart/cart.html')

cart/templates/cart/cart.html
{% extends 'main/base.html' %}

{% block title %}Cart | {% endblock %}

{% block content %}



<section class="section pt-1">
    <h1 class="title">Cart</h1>
        {% if cart %}
        <div class="box is-multiline mb-12">
            <div class="container">
                <div class="table">
                    <table class="table is-fullwidth">
                        <thead>
                            <th></th>
                            <th>Item</th>
                            <th>Description</th>
                            <th>Seller</th>
                            <th class="has-text-right">Price</th>
                            <th class="has-text-right">Quantity</th>
                            <th class="has-text-right">Extended Price</th>
                            <th class="is-narrow"></th>
                        </thead>
                        <tbody>
                            {% for cart_item in cart %}
                                <tr>
                                    <td>
                                        {% if cart_item.listing.image %}
                                        <figure class="image is-64x64 mb-4">
                                            <img src="{{ cart_item.listing.image.image }}">
                                        </figure>
                                        {% else %}
                                        <figure class="image is-64x64 mb-4">
                                            <img src="{{ cart_item.listing.pinventory_content.item.image.image }}">
                                        </figure>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {{ cart_item.listing.pinventory_content.item.name }}
                                    </td>
                                    <td>
                                        {% if cart_item.listing.descrip %}
                                            {{ cart_item.listing.descrip }}
                                        {% endif %}
                                    </td>
                                    <td>{{ cart_item.listing.pinventory_content.pinventory.owner.username }}</td>
                                    <td class="has-text-right">
                                        ${{ cart_item.listing.price|floatformat:2 }}
                                    </td>
                                    <td class="has-text-right">
                                        {{ cart_item.quantity }}
                                        <a href="?change_quantity={{ cart_item.listing.id }}&quantity=-1">-</a>
                                        <a href="?change_quantity={{ cart_item.listing.id }}&quantity=1">+</a>
                                    </td>
                                    <td class="has-text-right">
                                        ${{ cart_item.total_price|floatformat:2 }}
                                    </td>
                                    <td><a href="?remove_from_cart={{ cart_item.listing.id }}" class="delete">Remove</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                            <tfoot>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td class="has-text-right"><strong>Subtotal</strong></td>
                                    <td class="has-text-right" ><strong>${{ cart.get_total_price|floatformat:2 }}</strong></td>
                                    <td></td>
                                </tr>
                            </tfoot>
                    </table>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column is-3 is-offset-9">
                <a class="button is-success is-2 is-fullwidth" name="checkout" href="{% url 'orders:checkout' %}">
                    <span>Checkout</span>
                    <span class="icon is-small"><i class="fas fa-shopping-cart"></i></span>
                </a>
            </div>
        </div>
    {% else %}
        <div class="box mb-6">
            <div class="table">
                <table class="table is-fullwidth">
                    <thead>
                        <th></th>
                        <th>Item</th>
                        <th>Description</th>
                        <th>Seller</th>
                        <th class="has-text-right">Price</th>
                        <th class="has-text-right">Quantity</th>
                        <th class="has-text-right">Extended Price</th>
                        <th class="is-narrow"></th>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <p class="is-size-5 mb-5 mt-2">Your cart is empty...</p>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        {% endif %}
</section>
{% endblock %}