cart/urls.py
from django.urls import path
from django.contrib.auth import get_user_model
from . import views

User = get_user_model()

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
]

iheartpins/urls.py
from accounts import urls
import accounts
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views as auth_views
# from accounts import views as account_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # path('register/', account_views.register, name='register'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('cart/', include('cart.urls', namespace='cart'), name='cart'),
    path('orders/', include('orders.urls', namespace='orders'), name='orders'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('main.urls', namespace='main'), name='main'),
    path('', include('trans.urls', namespace='trans'), name='transaction')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from django.contrib.auth import get_user_model
from . import views

User = get_user_model()

app_name = 'orders'

urlpatterns = [
    path('checkout/', views.payment, name='checkout'),
    path('success/', views.success, name='success'),
]

orders/models.py
from django.db import models
from django.conf import settings
from trans.models import Listing
from accounts.models import Address, Person


User = settings.AUTH_USER_MODEL

class Order(models.Model):
    buyer = models.ForeignKey(User, related_name='orders', on_delete=models.DO_NOTHING)
    buyer_firstname = models.CharField(max_length=255)
    buyer_lastname = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, blank=True)
    ship_to = models.ForeignKey(Address, related_name='orders', on_delete=models.DO_NOTHING)

    status = models.CharField(max_length=255, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    cart_total = models.DecimalField(max_digits=10, decimal_places=2)
    shipping = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    sales_tax = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_paid = models.DecimalField(max_digits=10, decimal_places=2)
    paid = models.BooleanField(default=False)

    # order_key = models.CharField(max_length=255)
    gateway = models.CharField(max_length=255, blank=True, null=True)
    payment_intent = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        ordering = ['-date_created']

    def __str__(self):
        return '%s' % self.id

    def get_total_quantity(self):
        return sum(int(item.quantity) for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, related_name='order_item', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    seller = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    seller_payout = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    payout_complete = models.BooleanField(default=False)

    def __str__(self):
        return '%s' % self.listing

    def get_total_price(self):
        return self.price * self.quantity

orders/forms.py
from django import forms

class CheckoutForm(forms.Form):
    buyer = forms.IntegerField()
    buyer_name = forms.IntegerField()
    email = forms.EmailField(max_length=255)
    ship_to = forms.IntegerField()
    subtotal = forms.DecimalField()
    shipping = forms.DecimalField()
    sales_tax = forms.DecimalField()
    total_paid = forms.DecimalField()
    gateway = forms.CharField(max_length=255)





    #
    # for cart_item in Cart(request):
    #     OrderItem.objects.create(
    #         order=order,
    #         listing=cart_item['listing'],
    #         quantity=cart_item['quantity'],
    #         price=cart_item['listing'].price,
    #         seller=cart_item['listing'].pinventory.owner,

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.conf import settings
from django.http import request, HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json
import ast

from decimal import Decimal

from paypalcheckoutsdk.orders import OrdersGetRequest
from .paypal import PayPalClient

from cart.cart import Cart
from trans.models import Listing
from main.models import PinventoryContent
from .utilities import checkout
from django.contrib.auth import get_user_model
from .shippingRate import getShippingRate
from .taxRate import get_tax
from accounts.models import Address, Person

User = get_user_model()

@login_required
def payment(request):
    cart = Cart(request)
    user = request.user
    email = user.email
    ship_to = request.user.name.address.get(is_shipping=True)
    cart_total = float(cart.get_total_price())
    shipping = 0.00
    sales_tax = 0.00
    seller_items = []
    sellers = []
    # seller_addresses = []
    for cart_item in Cart(request):
        item_seller = cart_item['seller']
        item_price = cart_item['listing']['price']
        seller_items.append((item_seller, item_price))
        if item_seller not in sellers:
            sellers.append(item_seller)

    for seller in sellers:
        slr = json.loads(seller)
        person = Person.objects.get(pk=slr['id'])
        seller_address = person.address.filter(is_shipping=True)
        seller_total = [item_price for item_seller, item_price in seller_items if seller == item_seller]
        # sales_tax_by_seller = get_tax(senderAddress=seller_address, receiverAddress=ship_to, orderAmount=seller_total, shippingAmount=shipping)

    total_paid = cart_total + shipping + sales_tax

    if request.method == 'POST':

        data = json.loads(request.body)
        gateway = data['gateway']
        payment_intent = data['order_id']

        order = checkout(request, user, cart_total, shipping, sales_tax, total_paid, gateway, payment_intent)
        order.save()

        if gateway == 'paypal':
            PPClient = PayPalClient()
            req = OrdersGetRequest(payment_intent)
            response = PPClient.client.execute(req)

            if response.result.status == 'COMPLETED':
                order.paid = True
                order.status = 'paid'
                order.save()
                cart.clear()

                jsonresponse = {'success': True}
                return JsonResponse(jsonresponse)

            else:
                jsonresponse = {'success': False}
                return JsonResponse(jsonresponse)

        else:
            jsonresponse = {'success': False}
            return JsonResponse(jsonresponse)
    else:
        context = {
            'cart': cart,
            'user': user,
            'ship_to': ship_to,
            'shipping': shipping,
            'sales_tax': sales_tax,
            'total_paid': total_paid,
            'paypal_pub_key': settings.PAYPAL_PUB_KEY,
        }
        return render(request, 'orders/checkout.html', context)



def success(request):
    return render(request, 'orders/success.html', {})

orders/templates/orders/checkout.html
{% extends 'main/base.html' %}

{% block title %}Checkout | {% endblock %}

{% block content %}

<section class="section pt-1">
<h1 class="title mb-2">Checkout</h1>

    <a class="button is-white mb-4 pl-0" href="{% url 'cart:cart' %}">< Back to cart</a>
    {% if cart %}
    <div class="columns">
        <div class="column is-two-thirds">
            <div class="box">
                <table class="table is-fullwidth">
                    <thead>
                        <th></th>
                        <th>Item</th>
                        <th>Seller</th>
                        <th class="has-text-right">Price</th>
                        <th class="has-text-right">Quantity</th>
                        <th class="has-text-right">Extended Price</th>

                    </thead>
                    <tbody>
                        {% for cart_item in cart %}
                            <tr>
                                <td>
                                    {% if cart_item.listing.image %}
                                    <figure class="image is-64x64 mb-4">
                                        <img src="{{ cart_item.listing.image.image }}">
                                    </figure>
                                    {% else %}
                                    <figure class="image is-64x64 mb-4">
                                        <img src="{{ cart_item.listing.pinventory_content.item.image.image }}">
                                    </figure>
                                    {% endif %}
                                </td>
                                <td>
                                    {{ cart_item.listing.pinventory_content.item.name }}
                                </td>
                                <td>{{ cart_item.listing.pinventory_content.pinventory.owner.username }}</td>
                                <td class="has-text-right">
                                    $ {{ cart_item.listing.price|floatformat:2 }}
                                </td>
                                <td class="has-text-right">
                                    {{ cart_item.quantity }}
                                </td>
                                <td class="has-text-right">
                                    $ {{ cart_item.total_price|floatformat:2 }}
                                </td>

                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="has-text-right"><strong>Subtotal</strong></td>
                            <td class="has-text-right"><strong>${{ cart.get_total_price|floatformat:2 }}</strong></td>

                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <div class="column is-one-third">
            <div class="box">

                <div class="columns">

                    <div class="column">
                        <p><strong>Ship to:</strong></p>
                        {% if not user == AnonymousUser %}
                        <p class="ml-5 mt-2">{{ user.name }}<br>
                            {{ ship_to.street1 }}<br>
                                {% if ship_to.street2 %}
                                    {{ ship_to.street2 }}<br>
                                {% endif %}
                            {{ ship_to.city }}, {{ ship_to.state }} {{ ship_to.postalcode }}</p><br>
                        {% else %}
                        <p class="ml-5 mt-2">AnonymousUser</p><br>
                        {% endif %}
                        <p></p><br>

                        <div class="columns is-mobile">
                            <div class="column is-half">
                                <p><strong>Subtotal</strong></p><br>
                                <p><strong>Shipping</strong></p><br>
                                <p><strong>Sales Tax</strong></p><br>
                                <p><strong>Total</strong></p><br>
                            </div>
                            <div class="column">
                                <p class="has-text-right"><strong>$ {{ cart.get_total_price|floatformat:2 }}</strong></p><br>
                                <p class="has-text-right"><strong>$ {{ shipping|floatformat:2 }}</strong></p><br>
                                <p class="has-text-right"><strong>$ {{ sales_tax|floatformat:2 }}</strong></p><br>
                                <p class="has-text-right"><strong>$ {{ total_paid|floatformat:2 }}</strong></p>
                            </div>
                        </div>
                    </div>

                </div>
                <div id="paypal-button-container"></div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="box mb-6">
    </div>
</section>
    {% endif %}
{% endblock %}

{% block scripts%}
    <script
        src="https://www.paypal.com/sdk/js?client-id={{ paypal_pub_key }}&disable-funding=credit">
    </script>
<script>

    paypal.Buttons({
        onClick: () => {
        },
        createOrder: function(data, actions) {
             return actions.order.create({
                purchase_units: [{
                    "amount": {
                        "value": '{{ cart.get_total_price|floatformat:2 }}'
                    }
                }]
            })
        },
        onApprove: (data, actions) => {
            const formdata = {
                'gateway': 'paypal',
                'order_id': data.orderID
            }
            console.log(formdata)
            return actions.order.capture().then(function(details){
                return fetch('/orders/checkout/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify(formdata)
                })
                .then(function(response) {
                    return response.json()
                    console.log(response)
                })
                .then(function(result) {
                    window.location.href = '{% url 'orders:success' %}';
                })
                .catch(function(error) {
                    console.log('error:', error);
                });
            });
        }
    }).render('#paypal-button-container')

</script>

{% endblock %}

orders/templates/orders/process_payment.html
{% extends 'main/base.html' %}

{% block title %}Cart | {% endblock %}

{% block content %}
<h1 class="title">{{ data }}</h1>
<p>payment complete</p>

{{ data }}
{{ order_id }}

{% endblock %}

{% block scripts %}
{% endblock %}

orders/templates/orders/success.html
{% extends 'main/base.html' %}

{% block title %}Cart | {% endblock %}

{% block content %}
<p>payment successful</p>
<p>{{ body }}</p>
<p>{{ order_id }}</p>

{% endblock %}

{% block scripts %}
{% endblock %}