cart/urls.py
from django.urls import path
from django.contrib.auth import get_user_model
from . import views

User = get_user_model()

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
]

iheartpins/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import get_user_model


User = get_user_model()

app_name = 'main'

urlpatterns = [
    path('home/', views.home, name="home"),
    path('pinventory/', views.pinventory, name='pinventory'),
    path('search/', views.search_pindex, name='search'),
    path('item-detail/<slug:item_slug>/', views.item_detail, name='item'),
    path('submit-item/', views.submit_item, name='submit'),
    path('contact-us/', views.contact_us, name="contact"),
    path('', views.home, name="home"),
]

iheartpins/urls.py
from accounts import urls
import accounts
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views as auth_views
# from accounts import views as account_views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # path('register/', account_views.register, name='register'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('cart/', include('cart.urls', namespace='cart'), name='cart'),
    path('orders/', include('orders.urls', namespace='orders'), name='orders'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('main.urls', namespace='main'), name='main'),
    path('', include('trans.urls', namespace='trans'), name='transaction')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('home/', views.home, name="home"),
    path('landing/', views.landing, name="landing"),
    path('pinventory/', views.pinventory, name='pinventory'),
    path('search/', views.search_pindex, name='search'),
    path('item-detail/<slug:item_slug>/', views.item_detail, name='item'),
    path('submit-item/', views.submit_item, name='submit'),
    path('contact-us/', views.contact_us, name="contact"),
    path('', views.homepage, name="home"),
]

main/forms.py
from django import forms
from django.db import models
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset
from crispy_forms.bootstrap import InlineRadios, Div
from .models import ItemImage, Pin, PinSet, Item


User = get_user_model()

TYPE_CHOICES = (
    (0, 'Pin'),
    (1, 'Pin Set'),
)


def get_formhelper_submit():
    helper = FormHelper()
    layout = Layout()
    fieldset = Fieldset('SelectType')


class SelectType(forms.ModelForm):
    type = forms.ChoiceField(choices=TYPE_CHOICES, widget=forms.RadioSelect(attrs={'onchange':'submit();'}),initial=0)
    class Meta:
        model = Item
        fields = ['type']


class SubmitPin(forms.ModelForm):
    class Meta:
        model = Pin
        fields = [
            'name',
            'source',
            'release_date',
            'release_notes',
            'edition_type',
            'edition_size',
            'original_price',
            'is_retired',
            'retired_date',
            'has_ap',
            'has_pp',
            'is_included_in_set',
            'is_fantasy',
        ]

class SubmitPinSet(forms.ModelForm):
    class Meta:
        model = PinSet
        fields = [
            'name',
            'source',
            'release_date',
            'release_notes',
            'edition_type',
            'edition_size',
            'original_price',
            'is_retired',
            'retired_date',
            'has_ap',
            'has_pp',
            'qty_in_set',
        ]



class SubmitImage(forms.ModelForm):
    image = forms.ImageField()
    class Meta:
        model = ItemImage
        fields = ['image',]
    pass

iheartpins/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.db.models import Q
from .models import PinventoryContent, ItemImage, Item
from .forms import SubmitPin, SubmitPinSet, SelectType, SubmitImage
from django.contrib.auth import get_user_model
from django.contrib import messages
import random


User = get_user_model()

def home(request):
    all_items = list(Item.objects.all())
    sample_items = random.sample(all_items, 6)
    images_primary = ItemImage.objects.filter(item__in=sample_items, is_primary=True)

    return render(request, 'main/home.html',{
        'sample_items':sample_items,
        'images_primary':images_primary,
    })

def search_pindex(request):
    query = request.GET.get('query', '')
    items = Item.objects.filter(Q(name__icontains=query))
    query_item_images = ItemImage.objects.filter(item__in=items, is_primary=True)

    return render(request, 'main/pindex_search_results.html', {
        'items':items,
        'query':query,
        'query_item_images':query_item_images,
    })


@login_required
def pinventory(request):
    pinventory = request.user.pinventory
    v = PinventoryContent.objects.filter(pinventory=pinventory)
    v_items = Item.objects.filter(pinventorycontent__in=v)
    v_images = ItemImage.objects.filter(item__in=v_items, is_primary=True)

    return render(request, 'main/pinventory.html', {
        'v':v,
        'pinventory':pinventory,
        'v_items':v_items,
        'v_images':v_images,
    })


def item_detail(request, item_slug):
    item = get_object_or_404(Item, slug=item_slug)
    main_item_images = ItemImage.objects.filter(item=item)
    main_item_primary_image = main_item_images.get(is_primary=True)
    similar_item_images = list(ItemImage.objects.filter(is_primary=True).exclude(item=item.id))
    if len(similar_item_images) >= 6:
        similar_item_images = random.sample(similar_item_images, 6)
        for item_image in similar_item_images:
            individual_item = item_image.item

    return render(request, 'main/item_detail.html', {
        'item':item,
        'main_item_images':main_item_images,
        'main_item_primary_image':main_item_primary_image,
        'similar_item_images':similar_item_images,
        'item_image':item_image,
        'individual_item':individual_item,
    })

@login_required
def submit_item(request):
    form1 = SelectType()
    form2 = SubmitPinSet()
    form3 = SubmitPin()
    ImageFormSet = modelformset_factory(ItemImage, SubmitImage, extra=5)
    formset = ImageFormSet(queryset=ItemImage.objects.none())
    if request.method == 'POST' and form1:
        form1 = SelectType(request.POST or None)
        formset = ImageFormSet(request.POST, request.FILES, queryset=ItemImage.objects.none())
        if form1.is_valid():
            if request.POST['type'] == '1':
                form2 = SubmitPinSet(request.POST or None)
                if form2.is_valid() and formset.is_valid():
                    item = form2.save(commit=False)
                    item.type = 1
                    item.submitted_by = request.user
                    item.slug = slugify(item.name)
                    item.save()
                    for form in formset.cleaned_data:
                        if form:
                            image = form['image']
                            photo = ItemImage(item=item, image=image)
                            photo.save()
                    messages.add_message(request, messages.SUCCESS, 'Request sumbitted successfully.')
                    return redirect('submit')
            else:
                form3 = SubmitPin(request.POST or None)
                if form3.is_valid() and formset.is_valid():
                    item = form3.save(commit=False)
                    item.type = 0
                    item.submitted_by = request.user
                    item.slug = slugify(item.name)
                    item.save()
                    for form in formset.cleaned_data:
                        if form:
                            image = form['image']
                            photo = ItemImage(item=item, image=image)
                            photo.save()
                    messages.add_message(request, messages.SUCCESS, 'Request sumbitted successfully.')
                    return redirect('submit')
    else:
        form3 = SubmitPin()
        form2 = SubmitPinSet()
        formset = ImageFormSet(queryset=ItemImage.objects.none())
    return render(request, 'main/submit_item.html', {
        'form1': form1,
        'form2': form2,
        'form3': form3,
        'formset': formset,
    })

def contact_us(request):
    return render(request, 'main/contact.html')

main/views.py
from django.http import request
from django.shortcuts import render, get_object_or_404, redirect
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.db.models import Q
from .models import PinventoryContent, ItemImage, Item
from .forms import SubmitPin, SubmitPinSet, SelectType, SubmitImage
from django.contrib.auth import get_user_model
from django.contrib import messages
import random


User = get_user_model()

def landing(request):
    return render(request, 'main/landing.html')


def homepage(request):
    return render(request, 'main/home.html')

def home(request):
    all_items = list(Item.objects.all())
    sample_items = random.sample(all_items, 6)
    images_primary = ItemImage.objects.filter(item__in=sample_items, is_primary=True)

    return render(request, 'main/home.html',{
        'sample_items':sample_items,
        'images_primary':images_primary,
    })

def search_pindex(request):
    print('Hello')
    query = request.GET.get('query', '')
    items = Item.objects.filter(Q(name__icontains=query))
    query_item_images = ItemImage.objects.filter(item__in=items, is_primary=True)

    return render(request, 'main/pindex_search_results.html', {
        'items':items,
        'query':query,
        'query_item_images':query_item_images,
    })


@login_required
def pinventory(request):
    pinventory = request.user.pinventory
    v = PinventoryContent.objects.filter(pinventory=pinventory)
    v_items = Item.objects.filter(pinventorycontent__in=v)
    v_images = ItemImage.objects.filter(item__in=v_items, is_primary=True)

    return render(request, 'main/pinventory.html', {
        'v':v,
        'pinventory':pinventory,
        'v_items':v_items,
        'v_images':v_images,
    })


def item_detail(request, item_slug):
    item = get_object_or_404(Item, slug=item_slug)
    main_item_images = ItemImage.objects.filter(item=item)
    main_item_primary_image = main_item_images.get(is_primary=True)
    similar_item_images = list(ItemImage.objects.filter(is_primary=True).exclude(item=item.id))
    if len(similar_item_images) >= 6:
        similar_item_images = random.sample(similar_item_images, 6)
        for item_image in similar_item_images:
            individual_item = item_image.item

    return render(request, 'main/item_detail.html', {
        'item':item,
        'main_item_images':main_item_images,
        'main_item_primary_image':main_item_primary_image,
        'similar_item_images':similar_item_images,
        'item_image':item_image,
        'individual_item':individual_item,
    })

@login_required
def submit_item(request):
    form1 = SelectType()
    form2 = SubmitPinSet()
    form3 = SubmitPin()
    ImageFormSet = modelformset_factory(ItemImage, SubmitImage, extra=5)
    formset = ImageFormSet(queryset=ItemImage.objects.none())
    if request.method == 'POST' and form1:
        form1 = SelectType(request.POST or None)
        formset = ImageFormSet(request.POST, request.FILES, queryset=ItemImage.objects.none())
        if form1.is_valid():
            if request.POST['type'] == '1':
                form2 = SubmitPinSet(request.POST or None)
                if form2.is_valid() and formset.is_valid():
                    item = form2.save(commit=False)
                    item.type = 1
                    item.submitted_by = request.user
                    item.slug = slugify(item.name)
                    item.save()
                    for form in formset.cleaned_data:
                        if form:
                            image = form['image']
                            photo = ItemImage(item=item, image=image)
                            photo.save()
                    messages.add_message(request, messages.SUCCESS, 'Request sumbitted successfully.')
                    return redirect('submit')
            else:
                form3 = SubmitPin(request.POST or None)
                if form3.is_valid() and formset.is_valid():
                    item = form3.save(commit=False)
                    item.type = 0
                    item.submitted_by = request.user
                    item.slug = slugify(item.name)
                    item.save()
                    for form in formset.cleaned_data:
                        if form:
                            image = form['image']
                            photo = ItemImage(item=item, image=image)
                            photo.save()
                    messages.add_message(request, messages.SUCCESS, 'Request sumbitted successfully.')
                    return redirect('submit')
    else:
        form3 = SubmitPin()
        form2 = SubmitPinSet()
        formset = ImageFormSet(queryset=ItemImage.objects.none())
    return render(request, 'main/submit_item.html', {
        'form1': form1,
        'form2': form2,
        'form3': form3,
        'formset': formset,
    })

def contact_us(request):
    return render(request, 'main/contact.html')

main/templates/main/add-item.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% crispy form form.get_formhelper %}

{% block title %}Submit Request | {% endblock title %}
{% block content %}
    <h1 class="title">Suggest a pin or set to add to the iheartpins Pindex</h1>
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <fieldset id="form1">
                    {{ form1|crispy }}
                </fieldset>
                    {% if form1.type.value == '1' %}
                        <fieldset id="form2">
                            {{ form2|crispy }}
                            {{ formset.management_form|crispy }}
                                {% for form in formset %}
                                    {{ form }} <br />
                                {% endfor %}
                        </fieldset>
                    {% else %}
                        <fieldset id="form3">
                            {{ form3|crispy }}
                            {{ formset.management_form|crispy }}
                                {% for form in formset %}
                                    {{ form }} <br />
                                {% endfor %}
                        </fieldset>
                    {% endif %}
            </div>
                <div class="field">
                    <div class="control">
                        <button class="button is-dark" type="submit">Submit Item</button>
                    </div>
                </div>
        </form>
{% endblock content%}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="img/logo.png" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="{% static 'css/slick.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>Home Page</title>
    </head>
<body> 
    <header>
        <div class="nav-links">
            <ul class="menus">
                <li><a href="/">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Blogs</a></li>
                <li><a href="{% url 'main:contact' %}">Contact</a></li>
            </ul>
            <ul class="header-btn">
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'account' %}">Account</a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                <li>
                    <a href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="hamburger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </header>
    {% block content %}
    {% endblock %}
    <script>
        const navSlide = () =>{
            const burger = document.querySelector('.hamburger');
            const nav = document.querySelector('.nav-links');
            const navLinks = document.querySelectorAll('.menus li');

            burger.addEventListener('click', () => {

                nav.classList.toggle('nav-active');

                navLinks.forEach((link,index)=>{
                if (link.style.animation) {
                    link.style.animation = '';
                } else {
                    link.style.animation = `navLinkFade 1.5s ease forwards ${index / 7 + 0.3}s`;
                }
            });
            burger.classList.toggle('toggle');
            });
        }
        navSlide();
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script>
        $('.slick-slides').slick({
            slidesToShow: 5,
            slidesToScroll: 1,
            autoplay: true,
            autoplaySpeed: 2000,
            speed:800,
            prevArrow:'<i class="fas fa-chevron-left    left-arrow">',
            nextArrow:'<i class="fas fa-chevron-right   right-arrow">',
            responsive: [
                {
                breakpoint: 768,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    // infinite: true,
                }
                },
                {
                breakpoint: 600,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                }
                },
                {
                breakpoint: 480,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                }
                }
            ]
        });
    </script>
</body>
</html>

main/templates/main/base_old.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <title>{% block title %}{% endblock title %}iheartpins.app</title>

        <link rel="shortcut icon" type="image/png" href="/media/images/I-love-heart-favicon-png.png">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
        <link rel="stylesheet" href="{% static 'styles/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'styles/css/brands.css' %}">

    </head>
    <body>
        <div class="block">
            <nav class="navbar is-primary">
                <div class="nav-left">
                    <div class="navbar-brand">
                        <a href="/" class="navbar-item">
                            <h1 class="title is-4">iheartpins</h1>

                            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="main-navbar">
                                <span aria-hidden="true"></span>
                                <span aria-hidden="true"></span>
                                <span aria-hidden="true"></span>
                            </a>
                        </a>
                    </div>
                </div>

                <div class="navbar-center">
                    <div class="navbar-item">
                        <form method="get" action="{% url 'main:search' %}">
                            <div class="field has-addons is-expanded">
                                <p class="control">
                                    <input type="text" class="input" placeholder="Search the Pindex..." name="query">
                                </p>
                                <p class="control">
                                    <button class="button is-dark">
                                        <span class="icon is-small"><i class="fas fa-search" aria-hidden="true"></i></span>
                                    </button>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="navbar-end">
                    <div class="navbar-item">
                        <a href="{% url 'cart:cart' %}" class="button is-dark" aria-hidden="true">
                            <span>Cart{% if cart %}({{ cart|length }}){% endif %}</span>
                                <span class="icon is-medium"><i class="fas fa-shopping-cart"></i></span>
                        </a>
                    </div>

                    <div class="navbar-item">
                        {% if user.is_authenticated %}
                            <a href="{% url 'main:pinventory' %}">{{ user.username }}</a>
                            <a href="{% url 'logout' %}" class="button is-dark">logout</a>

                        {% else %}
                            <a href="{% url 'login' %}" class="button is-dark">Sign In</a>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </div>
            <div>
                {% block content %}
                {% endblock %}
            </div>
        <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="notification is-success is-toast">{{ message }}</div>
                {% endfor %}
            {% endif %}
        </div>
    <script type="text/javascript" src="{% static 'scripts/main.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/8002f83e68.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'scripts/cart.js' %}"></script>

        {% block scripts %}
        {% endblock %}

    </body>
</html>

main/templates/main/contact.html
{% extends "main/base.html" %}

{% block title %}Contact Us | {% endblock title %}

{% block content %}
    <h1>Contact</h1>
{% endblock content %}

main/templates/main/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="img/logo.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Home Page</title>
</head>

<body>
    <header>
        <div class="nav-links">
            
            <ul class="menus">
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Blogs</a>
                </li>
                <li>
                    <a href="{% url 'main:contact' %}">Contact</a>
                </li>
            </ul>
            <ul>
                <li>
                   <form method="get" action="{% url 'main:search' %}" class="header-search">
                       <input type="text" name="query" id="" placeholder="Search Pins">
                       <button><i class="fas fa-search"></i></button>
                    </form>
                </li>
            </ul>
            <ul class="header-btn">
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'account' %}">Account</a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'login' %}">Login</a>
                </li>
                <li>
                    <a href="{% url 'register' %}">Register</a>
                </li>
                {% endif %}
            </ul>            
        </div>
        <div class="hamburger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </header>
    {% block main_content %}
    {% endblock main_content %}
    <script>
        const navSlide = () =>{
            const burger = document.querySelector('.hamburger');
            const nav = document.querySelector('.nav-links');
            const navLinks = document.querySelectorAll('.menus li');

            burger.addEventListener('click', () => {

                nav.classList.toggle('nav-active');

                navLinks.forEach((link,index)=>{
                if (link.style.animation) {
                    link.style.animation = '';
                } else {
                    link.style.animation = `navLinkFade 1.5s ease forwards ${index / 7 + 0.3}s`;
                }
            });
            burger.classList.toggle('toggle');
            });
        }
        navSlide();
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script>
        $('.slick-slides').slick({
            slidesToShow: 5,
            slidesToScroll: 1,
            autoplay: true,
            autoplaySpeed: 2000,
            speed:800,
            prevArrow:'<i class="fas fa-chevron-left    left-arrow">',
            nextArrow:'<i class="fas fa-chevron-right   right-arrow">',
            responsive: [
                {
                breakpoint: 768,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    // infinite: true,
                }
                },
                {
                breakpoint: 600,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                }
                },
                {
                breakpoint: 480,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                }
                }
            ]
        });
    </script>
    <script src="{% static 'js/product.js' %}"></script>
</body>
</html>

main/templates/main/home_old.html
{% extends "main/base.html" %}

{% block content %}
<h1 class="title">Home Page</h1>
    <div class="columns is-multiline mb-6">
        <div class="column is-12 mt-6 mb-6">
            <h2 class="is-size-3">Check out these pins!</h2>
        </div>
        {% for item_image in images_primary %}
            {% include 'main/parts/list_item.html' %}
        {% endfor %}
    </div>

{% endblock content %}

main/templates/main/pindex_search_results.html
{% extends 'main/header.html' %}
{% load static %}
{% block title %}Pindex Search Results | {% endblock %}

<!-- <div class="content-wrapper">
    <form method="get" action="{% url 'main:search' %}" class="search-box animate__animated animate__fadeInUp">
        <div class="search-inp">
            <input type="text"  placeholder="Search Pins..." name="query">
        </div>
        <button class="search-btn"><i class="fas fa-search"></i>Search</button>  
    </form>
</div> -->
{% block main_content %}

{% include "main/logo.html" %}
    <section class="container mt-5">
        <h2 class="is-size-3">Pindex Search Results</h2>
        <p>Search term: "{{ query }}"</p>
   
        <!-- <div class="columns is-multiline mb-6">
        <div class="column is-12 mt-6 mb-6">
            <h2 class="is-size-3">Pindex Search Results</h2>
            <h3>Search term: "{{ query }}"</h3>
        </div> -->
        <div class="container pt-5">
            {% if items %}
            {% for item_image in query_item_images %}
                {% include 'main/parts/list_item.html' %}
            {% endfor %}
            {% else %}
            <p>Didn't find what you were looking for?
                <a href="{% url 'main:submit' %}" class="text-center">Submit a request to add a pin to our Pindex.</a>
            </p>
            {% endif %}
        </div>
    </section>  
    <!-- </div> -->
{% endblock main_content %}

main/templates/main/pindex_search_results_old.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Pindex Search Results | {% endblock %}

{% block content %}

    <div class="content-wrapper">
        <form method="get" action="{% url 'main:search' %}" class="search-box animate__animated animate__fadeInUp">
            <div class="search-inp">
                <input type="text"  placeholder="Search Pins..." name="query">
            </div>
            <button class="search-btn"><i class="fas fa-search"></i>Search</button>  
        </form>
    </div>

    <section class="container">
        <h2 class="is-size-3">Pindex Search Results</h2>
        <p>Search term: "{{ query }}"</p>
   
        <!-- <div class="columns is-multiline mb-6">
        <div class="column is-12 mt-6 mb-6">
            <h2 class="is-size-3">Pindex Search Results</h2>
            <h3>Search term: "{{ query }}"</h3>
        </div> -->
        <div class="container pt-5">
            {% if items %}
            {% for item_image in query_item_images %}
                {% include 'main/parts/list_item.html' %}
            {% endfor %}
            {% else %}
            <p>Didn't find what you were looking for?
                <a href="{% url 'main:submit' %}">Submit a request to add a pin to our Pindex.</a>
            </p>
            {% endif %}
        </div>
    </section>  
    <!-- </div> -->
{% endblock %}